# Azure pipeline for PyLops-distributed

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip setuptools wheel django
    pip install -r requirements-dev.txt
    pip install .
  displayName: 'Install prerequisites and library'

- script: |
    python setup.py test
  condition: succeededOrFailed()
  displayName: 'Run tests'
