name: pylops-distributed
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.6.4
  - numpy>=1.15.0
  - scipy>=1.1.0
  - numba
  - icc_rt
  - dask>=2.0.0
  - dask-jobqueue
  - pylops
